###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a8-controller
  labels:
    name: a8-controller
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: a8-controller
    spec:
      hostname: a8-controller
      containers:
      - name: a8-controller
        image: amalgam8/a8-controller:1.1.0
        ports:
         - containerPort: 8080
         - containerPort: 31200
        env:
         - name: A8_LOG_LEVEL
           value: info
         - name: A8_DATABASE_TYPE
           value: redis
         - name: A8_DATABASE_HOST
           value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: a8-controller
  labels:
    name: a8-controller
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 31200
    name: appport
    targetPort: 31200
  selector:
    name: a8-controller
