###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a8-registry
  labels:
    name: a8-registry
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: a8-registry
    spec:
      hostname: a8-registry
      containers:
      - name: a8-registry
        image: amalgam8/a8-registry:1.1.0
        ports:
         - containerPort: 8080
         - containerPort: 31300
        env:
         - name: A8_STORE
           value: redis
         - name: A8_STORE_ADDRESS
           value: redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: a8-registry
  labels:
    name: a8-registry
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 31300
    name: appport
    targetPort: 31300
  selector:
    name: a8-registry
