###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      hostname: redis
      containers:
      - name: redis
        image: redis:3.0.7
        ports:
         - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis
