###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: v1
kind: Service
metadata:
  name: cam-auth-service
  labels:
    name: cam-auth-service
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: 9443
    name: secure-port
    targetPort: 9443
  - port: 9080
    name: normal-port
    targetPort: 9080
  - port: 3100
    name: normal-port1
    targetPort: 3100
  selector:
    name: cam-auth-service
