###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

---
apiVersion: v1
kind: Service
metadata:
  name: cam-proxy
  labels:
    name: cam-proxy
  namespace: {{ .Values.service.namespace }}
spec:
  type: NodePort
  ports:
  - port: 30000
    #targetPort: 30000
    #nodePort: 30000
    targetPort: 30000
    nodePort: 30000
  selector:
    name: cam-proxy
