###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: v1
kind: Service
metadata:
  name: cam-iaas
  labels:
    name: cam-iaas
  namespace: {{ .Values.service.namespace }}
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30002
  selector:
    name: cam-iaas
