###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: v1
kind: Service
metadata:
  name: cam-mongo
  labels:
    name: cam-mongo
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: cam-mongo
