kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cam-logs-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
#  selector:
#    matchLabels:
#      use: cam-log
